server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defautlZone: http://localhost:8761/eureka

spring:
  application:
    name: applicationClient

applicationClient:
 ribbon:
    eureka:
       enabled: true
    ServerListRefreshInterval: 15000
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList